version: '3.8'

services:
  bert-qa-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: bert-qa-api
    ports:
      - "5000:5000"
    volumes:
      - ../models:/app/models
      - ../cache:/app/cache
      - ../logs:/app/logs
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - HF_HOME=/app/cache/huggingface
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - bert-qa-network

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - bert-qa-network

  nginx:
    image: nginx:alpine
    container_name: bert-qa-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - bert-qa-api
    restart: unless-stopped
    networks:
      - bert-qa-network

volumes:
  ollama-data:
    driver: local

networks:
  bert-qa-network:
    driver: bridge
